# Encodage SQL
spring.sql.init.encoding=UTF-8

# Base de données PostgreSQL (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API REST
spring.data.rest.base-path=/api
spring.data.rest.defaultMediaType=application/json

# Port Render
server.port=${PORT:8080}

# Mailgun
mailgun.api.key=${MAILGUN_API_KEY:}
mailgun.domain=${MAILGUN_DOMAIN:}
mailgun.base-url=https://api.mailgun.net

# JSON format
spring.jackson.serialization.indent-output=true